// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7KCUXdt8llN9pDwD6MDQylz6SgIQ-zD0',
    appId: '1:969007208930:web:4e34ddfb4c02a97e2a01bb',
    messagingSenderId: '969007208930',
    projectId: 'educat-9121e',
    authDomain: 'educat-9121e.firebaseapp.com',
    storageBucket: 'educat-9121e.firebasestorage.app',
    measurementId: 'G-492Y2Y41YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYJTDE9vLEfjXHm5w0OJohcl2PnXbKQaE',
    appId: '1:969007208930:android:1d5b59be10a3324f2a01bb',
    messagingSenderId: '969007208930',
    projectId: 'educat-9121e',
    storageBucket: 'educat-9121e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4ro-EzDytQQMjHuDfQ1IO6s5KfnrFSY',
    appId: '1:969007208930:ios:69ee3f759362c1f52a01bb',
    messagingSenderId: '969007208930',
    projectId: 'educat-9121e',
    storageBucket: 'educat-9121e.firebasestorage.app',
    iosBundleId: 'com.example.educatmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4ro-EzDytQQMjHuDfQ1IO6s5KfnrFSY',
    appId: '1:969007208930:ios:69ee3f759362c1f52a01bb',
    messagingSenderId: '969007208930',
    projectId: 'educat-9121e',
    storageBucket: 'educat-9121e.firebasestorage.app',
    iosBundleId: 'com.example.educatmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7KCUXdt8llN9pDwD6MDQylz6SgIQ-zD0',
    appId: '1:969007208930:web:4c576190f5d0401c2a01bb',
    messagingSenderId: '969007208930',
    projectId: 'educat-9121e',
    authDomain: 'educat-9121e.firebaseapp.com',
    storageBucket: 'educat-9121e.firebasestorage.app',
    measurementId: 'G-WDQ0871DBT',
  );
}
